tqList = {
    "chrome.exe": "谷歌浏览器", 
    "firefox.exe": "火狐浏览器", 
    "msedge.exe": "火狐浏览器", 
    "Telegram.exe": "Telegram", 
    "WeChat.exe": "微信客户端", 
    "WeChatStore.exe": "微信客户端", 
    "aDrive.exe": "阿里网盘", 
    "pCloud.exe": "pCloud网盘", 
    "baidunetdisk.exe": "百度网盘", 
    "baidunetdiskhost.exe": "百度网盘", 
    "baidunetdiskrender.exe": "百度网盘", 
    "yundetectservice.exe": "百度云管家", 
    "wps.exe": "WPSOffice办公套件", 
    "wpscloudsvr.exe": "WPSOffice云服务", 
    "AnyDesk.exe": "AD远程控制软件", 
    "tv_w32.exe": "TV远程控制软件", 
    "tv_x64.exe": "TV远程控制软件", 
    "TeamViewer.exe": "TV远程控制软件", 
    "TeamViewer_Service.exe": "TV远程控制软件", 
    "SunloginClient.exe": "向日葵程控制软件", 
    "ToDesk.exe": "ToDesk程控制软件", 
    "ToDesk_Service.exe": "ToDesk服务", 
    "ToDesk_Session.exe": "ToDesk会话", 
    "ToDesk_Lite.exe": "ToDesk绿色版", 
    "notepad++.exe": "Notepad++编辑器",
    "vmware.exe": "VMware虚拟机", 
    "vmware-tray.exe": "VMware虚拟机", 
    "vmware-vmx.exe": "VMware虚拟机", 
    "vmware-authd.exe": "VMware虚拟机", 
    "vmware-unity-helper.exe": "VMware虚拟机", 
    "vmware-usbarbitrator64.exe": "VMware虚拟机", 
    "VirtualBox.exe": "VirtualBox虚拟机", 
    "VBoxSVC.exe": "VirtualBox虚拟机", 
    "VBoxSDS.exe": "VirtualBox虚拟机", 
    "SGTool.exe": "搜狗输入法-属性设置工具", 
    "SGDownload.exe": "搜狗输入法-修复更新工具", 
    "pinyinup.exe": "搜狗输入法-网络更新程序", 
    "SogouCloud.exe": "搜狗输入法-云计算代理", 
    "SogouComMgr.exe": "搜狗输入法-工具箱", 
    "SGRender.exe": "搜狗输入法-用户登录", 
    "QQPYUserCenter.exe": "QQ拼音输入法-个人中心", 
    "QQPYLiveUp.exe": "QQ拼音输入法-升级工具", 
    "QQPYConfig.exe": "QQ拼音输入法-属性设置", 
    "QQPYToolbox.exe": "QQ拼音输入法-工具箱", 
    "QQPYCloud.exe": "QQ拼音云输入-客户端", 
    "HwsHostPanel.exe": "护卫神主机卫士", 
    "HwsHostMaster.exe": "护卫神主机卫士", 
    "建站助手V4.0.exe": "西部数码建站助手",
    "红帆自定义表单设计器.exe": "红帆OA",
    "gpstool.exe": "某GPS定位工具", 
    "GServer.exe": "EXLIVE位置服务平台", 
    "phpStudy.exe": "phpStudy集成环境", 
    "xampp-control.exe": "XAMPP集成环境", 
    "python.exe": "Python环境", 
    "httpd.exe": "Apache环境", 
    "nginx.exe": "Nginx环境", 
    "mysql.exe": "MySQL数据库", 
    "mysqld.exe": "MySQL数据库", 
    "sqlservr.exe": "MSSQL数据库", 
    "SQLAGENT90.EXE": "MSSQL代理服务",
    "mongod.exe": "MongoDB数据库", 
    "SQL-Front.exe": "MySQL数据库管理工具", 
    "SQLyogCommunity.exe": "SQLyogCommunity数据库管理工具", 
    "navicat.exe": "Navicat数据库管理工具", 
    "Ssms.exe": "SQL Server Management Studio", 
    "sqlcmd.exe": "SQL Server命令行工具", 
    "FileZilla Server.exe": "FileZilla Server-FTP", 
    "FileZilla Server Interface.exe": "FileZilla Server-FTP", 
    "ServUDaemon.exe": "Serv-U-FTP", 
    "G6FTPServer.exe": "G6FTP-FTP", 
    "G6FTPTray.exe": "G6FTP-FTP",  
    "flashfxp.exe": "FlashFXP-FTP",
    "WinSCP.exe": "WinSCP-SSH", 
    "hfs.exe": "Http File Server-HTTP", 
    "Xshell.exe": "Xshell终端软件", 
    "XshellCore.exe": "Xshell终端软件", 
    "CloudClient.exe": "华为云桌面-客户端",
    "BtTools.exe": "宝塔面板Windows工具箱",
    "npc.exe": "内网穿透工具NPS客户端",
    "nps.exe": "内网穿透工具NPS服务端",
    "frpc.exe": "内网穿透工具FRP客户端",
    "frps.exe": "内网穿透工具FRP服务端",
    "finalshell.exe": "FinalShell SSH工具",
    "SangforUDProtectEx.exe": "深信服VPN升级程序",
    "SangforPromoteService.exe": "深信服VPN",
    "zabbix_agentd.exe": "Zabbix客户端",
};